# Generated by Django 4.0 on 2021-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
